version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/knowledge/faiss_index:/app/knowledge/faiss_index
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: wizraven-network